Case_study/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Case_study.Models
{
    public class Flight
    {
        [Key]
        public int Id { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string Airplane { get; set; }

        public DateTime departure { get; set; }
        public string date { get; set; }
        public string type { get; set; }
        public int price { get; set; }
        public string Araival { get; set; }
        public string Duration { get; set; }
    }
}

Case_study/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Case_study.DAL;
using Case_study.Models;

namespace Case_study.Controllers
{
    
    public class FlightsController : Controller
    {
        private Case_studyContext db = new Case_studyContext();

        [AllowAnonymous]
        public ActionResult Search(string source,string des,DateTime dep)
        {
            DateTime date_t = dep.Date;
            string date = date_t.ToString("d");
            var res = db.Flights.Where(s => s.source == source && s.destination == des && s.date == date).ToList();
            
            return View("Index",res);

        }
        [Authorize]
        public ActionResult Status()
        {
            Random r = new Random();
            int rInt = r.Next(5000, 100000); //for ints
            int range = 100;
            double rDouble = r.NextDouble() * range;
            //var identity = (ClaimsIdentity)User.Identity;
            //var role = identity.FindFirst(ClaimTypes.Email).Value;
            return View(rInt);
        }
        [AllowAnonymous]
        // GET: Flights
        public ActionResult Index()
        {
            return View(db.Flights.ToList());
        }
        [Authorize]
        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // GET: Flights/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,source,destination,Airplane,departure,type,price")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                DateTime date_t = flight.departure.Date;
                string date = date_t.ToString("d");
                flight.date = date;
                db.Flights.Add(flight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(flight);
        }
        [Authorize(Roles ="Admin")]
        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,source,destination,Airplane,departure,type,price")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                DateTime date_t = flight.departure.Date;
                string date = date_t.ToString("d");
                flight.date = date;
                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(flight);
        }
        [Authorize(Roles = "Admin")]
        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }
        [Authorize(Roles = "Admin")]
        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flight flight = db.Flights.Find(id);
            db.Flights.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Case_study/Views/Flights/Create.cshtml
@model Case_study.Models.Flight

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<div style="padding-top:9%;padding-left:25%; font-size:24px">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Flight</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.source, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.source, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.source, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.destination, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.destination, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.destination, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Airplane, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Airplane, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Airplane, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.departure, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.departure, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.departure, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Case_study/Views/Flights/Delete.cshtml
@model Case_study.Models.Flight

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
 <div style="padding-top:9%;padding-left:25%; font-size:24px">
    <h4>Flight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.source)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.source)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Airplane)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Airplane)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.departure)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.departure)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Case_study/Views/Flights/Details.cshtml
@model Case_study.Models.Flight

@{
    var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
    ViewBag.Title = "Details";

}
<script type="text/javascript" src="~/JS/JavaScript.js"></script>
<style>
    @@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Bree+Serif&family=EB+Garamond:ital,wght@0,500;1,800&display=swap');


body {
background: #DFC2F2;
	background-image: linear-gradient( to right, #ffffb3,#ffe6e6);
	background-attachment: fixed;
	background-size: cover;

	}

#container{
	box-shadow: 0 15px 30px 1px grey;
	background: rgba(255, 255, 255, 0.90);
	text-align: center;
	border-radius: 5px;
	overflow: hidden;
	margin: 5em auto;
	height: 350px;
	width: 700px;


}



.product-details {
	position: relative;
	text-align: left;
	overflow: hidden;
	padding: 30px;
	height: 100%;
	float: left;
	width: 40%;

}

#container .product-details h1{
	font-family: 'Bebas Neue', cursive;
	display: inline-block;
	position: relative;
	font-size: 30px;
	color: #344055;
	margin: 0;

}

#container .product-details h1:before{
	position: absolute;
	content: '';
	right: 0%;
	top: 0%;
	transform: translate(25px, -15px);
	font-family: 'Bree Serif', serif;
	display: inline-block;
	background: #ffe6e6;
	border-radius: 5px;
	font-size: 14px;
	padding: 5px;
	color: white;
	margin: 0;
	animation: chan-sh 6s ease infinite;

}






.hint-star {
	display: inline-block;
	margin-left: 0.5em;
	color: gold;
	width: 50%;
}


#container .product-details > p {
font-family: 'EB Garamond', serif;
	text-align: center;
	font-size: 18px;
	color: #7d7d7d;

}
.control{
	position: absolute;
	bottom: 20%;
	left: 22.8%;

}
.btn {

	transform: translateY(0px);
	transition: 0.3s linear;
	background:  #809fff;
	border-radius: 5px;
  position: relative;
  overflow: hidden;
	cursor: pointer;
	outline: none;
	border: none;
	color: #eee;
	padding: 0;
	margin: 0;

}

.btn:hover{transform: translateY(-6px);
	background: #1a66ff;}

.btn span {
	font-family: 'Farsan', cursive;
	transition: transform 0.3s;
	display: inline-block;
  padding: 10px 20px;
	font-size: 1.2em;
	margin:0;

}
.btn .price, .shopping-cart{
	background: #333;
	border: 0;
	margin: 0;
}

.btn .price {
	transform: translateX(-10%); padding-right: 15px;
}

.btn .shopping-cart {
	transform: translateX(-100%);
  position: absolute;
	background: #333;
	z-index: 1;
  left: 0;
  top: 0;
}

.btn .buy {z-index: 3; font-weight: bolder;}

.btn:hover .price {transform: translateX(-110%);}

.btn:hover .shopping-cart {transform: translateX(0%);}



.product-image {
	transition: all 0.3s ease-out;
	display: inline-block;
	position: relative;
	overflow: hidden;
	height: 100%;
	float: right;
	width: 45%;
	display: inline-block;
}

#container img {width: 100%;height: 100%;}

.info {
    background: rgba(27, 26, 26, 0.9);
    font-family: 'Bree Serif', serif;
    transition: all 0.3s ease-out;
    transform: translateX(-100%);
    position: absolute;
    line-height: 1.8;
    text-align: left;
    font-size: 105%;
    cursor: no-drop;
    color: #FFF;
    height: 100%;
    width: 100%;
    left: 0;
    top: 0;
}

.info h2 {text-align: center}
.product-image:hover .info{transform: translateX(0);}

.info ul li{transition: 0.3s ease;}
.info ul li:hover{transform: translateX(50px) scale(1.3);}

.product-image:hover img {transition: all 0.3s ease-out;}
.product-image:hover img {transform: scale(1.2, 1.2);}
</style>
<h2>Details</h2>


@*<script>
    function CallLogicApp() {
        let source = @Html.Raw(Model.source);
        console.log(source);
        let destination = @Html.Raw(Model.destination);
        let Airplane = @Html.Raw(Model.Airplane);
        let departure = @Html.Raw(Model.departure);
        let type =@Html.Raw(Model.type);
        let price = @Html.Raw(Model.price);


        var bookingconfirmation =
        {
            source: source,
            destination=destination,
            Airplane=Airplane,
            departure=departure,
            type=type,
            price=price
        };
        var url = "https://prod-61.eastus.logic.azure.com:443/workflows/0b75b563b00d4bbeb3241ae2f3ebc250/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=YTOHgOIVIGGWORRW0IMOLc51FA3aWs6E5cyqFnmS_CA";
        var http = new XMLHttpRequest();
        http.open('POST', url, true);
        //Send the proper header information along with the request
        http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        http.onreadystatechange = function () {//Call a function when the state changes.
            if (http.readyState == 4 && http.status == 200) {
                alert(http.responseText);
            }
        }
        http.send(JSON.stringify(bookingconfirmation));

</script>*@
<div>
    <h4>Trip</h4>
    <hr />

    <p>
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
        }
        @Html.ActionLink("Back to List", "Index")
    </p>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div style="padding-top:25px">
        <div id="container">

            <div class="product-details">

                <h1>Trip Details</h1>
                <span class="hint-star star">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                </span>
                <p class="information">@Model.source <span style="padding-left:1.5px">TO</span> @Model.destination</p>
                <p class="information">AT <span style="padding-left:1.5px"></span>@Model.departure</p>
                <p class="information">Type<span style="padding-left:1.5px"></span> @Model.type</p>
                <p class="information">Price <span style="padding-left:1.5px"></span>@Model.price INR</p>

                <div class="control">

                    <div id="paypal-btn"  ></div>
                    

                </div>

            </div>

            <div class="product-image">

                <img src="https://media.istockphoto.com/photos/passenger-airplane-taking-of-at-sunrise-picture-id1225840727?b=1&k=20&m=1225840727&s=170667a&w=0&h=dj8ErCdeGS_OG83VzmFZyulXwO62t1HdTYgSrkdbfGI=" alt="">


                <div class="info">
                    <h2> Description</h2>
                    <ul>
                        <li><strong>Plane : </strong>Boeing 777 </li>
                        <li><strong>Engine : </strong>2 Engine</li>
                        <li><strong>Capacity: </strong>250 people</li>
                        <li><strong>Material: </strong>Eco-Friendly</li>

                    </ul>
                </div>
            </div>

        </div>
    </div>


    @section Scripts{
        <script src="~/JS/JavaScript.js"></script>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<script>
        let _total = @Html.Raw(Model.price);
        paypal.Button.render({
            //Configure environment
            env: 'sandbox',
            client: {
                sandbox: 'ARNzAYF7qSkXdhaiPdIYTC2FcUzOpV5BhE4fgKvxSM2kT2gHtz1yoM8yXLvkLyq2RjZ9H0H7RwiLpAcH'
            },
            //Customize button
            locale: 'en_US',
            style: {
                size: 'small',
                color: 'gold',
                shape: 'pill'
            },
            commit: true,
            //Set up a payment
            payment: function (data, actions) {
                return actions.payment.create({
                    transactions: [{
                        amount: {
                            total: _total,
                            currency: 'USD'
                        }
                    }]
                });
            },
            //Execute the payment
            onAuthorize: function (data, actions) {

                return actions.payment.execute().then(function () {
                    var url = '@Url.Action("Status", "Flights", new { })';
                    window.location.href = url;
                });
            }
        }, '#paypal-btn')
    
</script>



}

Case_study/Views/Flights/Edit.cshtml
@model Case_study.Models.Flight

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<div style="padding-top:9%;padding-left:25%; font-size:24px">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Flight</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.source, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.source, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.source, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.destination, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.destination, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.destination, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Airplane, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Airplane, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Airplane, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.departure, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.departure, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.departure, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Case_study/Views/Flights/Index.cshtml
@model IEnumerable<Case_study.Models.Flight>

@{
    ViewBag.Title = "Index";
    
}

<style>
    @@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,100&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        width: 100%;
        display: flex;
        justify-content: center;
        font-family: 'Roboto', sans-serif;
        background-color: #adacac;
    }

    table {
        border-collapse: collapse;
    }

    .header_fixed {
        height: 700px;
        overflow: auto;
        margin-top: 30px;
        border: 1px solid #dddddd
    }

        .header_fixed thead th {
            position: sticky;
            top: 0;
            background-color: black;
            color: #E6E7E8;
            font-size: 15px;
        }


    th, td {
        border-bottom: 1px solid #dddddd;
        padding: 10px 20px;
        font-size: 14px;
    }

        td img {
            height: 60px;
            width: 60px;
            border: 5px solid #E6E7E8;
            border-radius: 100%;
        }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    tr:nth-child(odd) {
        background-color: #EDEEF1;
    }

    tr:hover td {
        color: #44b478;
        cursor: pointer;
        background-color: #FFFFFF;
    }

    tr button {
        border: none;
        padding: 7px 20px;
        border-radius: 20px;
        background-color: black;
        color: #E6E7E8;
    }

    ::-webkit-scrollbar {
        width: 6px;
    }

    ::-webkit-scrollbar-track {
        -webkit-box-shadow: insert 0 0 rgba(0,0,0,3);
    }

    ::-webkit-scrollbar-thumb {
        -webkit-box-shadow: insert 0 0 rgba(0,0,0,3);
    }
    a {
        color: inherit;
    }
</style>
<body background="https://anba.com.br/wp-content/uploads/2020/07/emiratesboeing777-300er.png">
    <h2>Your Flights</h2>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }

    @if (Model.Count() > 0)
    {
        <div style="padding-top:30px" class="header_fixed">


            <table class="table ">
                <thead>
                    <tr>
                        <th>Logo</th>
                        <th>
                            @Html.DisplayNameFor(model => model.source)
                        </th>
                        <th> @Html.DisplayNameFor(model => model.destination) </th>
                        <th> @Html.DisplayNameFor(model => model.Airplane) </th>
                        <th> @Html.DisplayNameFor(model => model.departure) </th>
                        <th>@Html.DisplayNameFor(model=>model.date)</th>
                        <th> @Html.DisplayNameFor(model => model.type) </th>
                        <th> @Html.DisplayNameFor(model => model.price) </th>
                        <th></th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td><img src="https://cdn-icons-png.flaticon.com/128/158/158225.png"></td>
                            <td> @Html.DisplayFor(modelItem => item.source) </td>
                            <td> @Html.DisplayFor(modelItem => item.destination) </td>
                            <td> @Html.DisplayFor(modelItem => item.Airplane) </td>
                            <td> @Html.DisplayFor(modelItem => item.departure) </td>
                            <td> @Html.DisplayFor(modelItem => item.date) </td>
                            <td> @Html.DisplayFor(modelItem => item.type) </td>
                            <td> @Html.DisplayFor(modelItem => item.price) </td>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <td> @Html.ActionLink("Edit", "Edit", new { id = item.Id }) | @Html.ActionLink("Delete", "Delete", new { id = item.Id }) </td>
                            }
                            else
                            {
                                <td><div class="btn btn-secondary btn-sm" style="border-radius:25px;color:black"> @Html.ActionLink("Details", "Details", new { id = item.Id })</div></td>
                            }
                        </tr>
                    </tbody>
                }



            </table>
        </div>
    }
    else
    {
        <h3>No Flights Are available</h3>
    }
    </body>